services:
  finance-tracker-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8082
    ports:
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /mnt/c/Users/sayyedulawwab/AppData/Roaming/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - /mnt/c/Users/sayyedulawwab/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /mnt/c/Users/sayyedulawwab/AppData/Roaming/ASP.NET/Https:/home/app/.aspnet/https:ro
      - /mnt/c/Users/sayyedulawwab/AppData/Roaming/ASP.NET/Https:/root/.aspnet/https:ro